import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/common/navbar";
import Sidebar from "@/components/common/sidebar";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          <Sidebar />
          <main className="flex-1 flex flex-col overflow-y-auto scrollbar-hide">
            <Navbar />
            <div className="flex-1">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
